"""
CAJAL Function for Open WebUI
https://github.com/open-webui/open-webui

This function adds CAJAL scientific paper generation capabilities to Open WebUI.
Paste this into Open WebUI: Admin Panel → Functions → Create Function

Title: CAJAL Paper Generator
Description: Generate scientific papers with structured sections and citations
"""

import json
import requests
from typing import List, Optional

class Pipe:
    def __init__(self):
        self.id = "cajal-paper-generator"
        self.name = "CAJAL"
        self.valves = {
            "CAJAL_MODEL": "cajal",
            "CAJAL_TEMPERATURE": 0.3,
            "CAJAL_MAX_TOKENS": 8192,
            "OLLAMA_HOST": "http://host.docker.internal:11434"
        }

    def pipes(self) -> List[dict]:
        return [{"id": self.id, "name": self.name}]

    def pipe(self, body: dict, user_message: str, model_id: str, messages: List[dict]) -> str:
        """Generate a scientific paper based on user input."""
        
        # Check if user wants a full paper or a section
        paper_sections = ["abstract", "introduction", "methods", "results", "discussion", "conclusion", "references"]
        
        system_prompt = """You are CAJAL (Cognitive Academic Journal Authoring Layer), a specialized scientific paper authoring assistant.

Generate publication-ready scientific papers with:
- Formal academic tone
- Proper structure (Abstract → Introduction → Methods → Results → Discussion → Conclusion → References)
- Real citations where possible
- Reproducible methodology
- Quantitative, evidence-based claims

Use markdown formatting with clear headers. Include YAML frontmatter for paper metadata."""

        # Build the prompt
        if any(section in user_message.lower() for section in paper_sections):
            # User requested a specific section
            prompt = f"{system_prompt}\n\nGenerate the following section for a scientific paper:\n\n{user_message}"
        else:
            # User wants a full paper
            prompt = f"{system_prompt}\n\nGenerate a complete scientific paper on:\n\n{user_message}\n\nInclude all sections: Abstract, Introduction, Related Work, Methodology, Results, Discussion, Conclusion, and References. Minimum 8 references with real citations."

        # Call Ollama
        try:
            response = requests.post(
                f"{self.valves['OLLAMA_HOST']}/api/generate",
                json={
                    "model": self.valves["CAJAL_MODEL"],
                    "prompt": prompt,
                    "stream": False,
                    "options": {
                        "temperature": self.valves["CAJAL_TEMPERATURE"],
                        "num_ctx": 32768,
                        "top_p": 0.9,
                        "repeat_penalty": 1.1
                    }
                },
                timeout=300
            )
            
            if response.status_code == 200:
                result = response.json()
                paper_text = result.get("response", "")
                
                # Add metadata footer
                footer = f"\n\n---\n*Generated by CAJAL (P2PCLAW Research Network) | Local LLM: {self.valves['CAJAL_MODEL']}*"
                return paper_text + footer
            else:
                return f"Error: Ollama returned status {response.status_code}. Make sure Ollama is running with the 'cajal' model."
                
        except requests.exceptions.ConnectionError:
            return "Error: Cannot connect to Ollama. Please ensure Ollama is running at " + self.valves['OLLAMA_HOST']
        except Exception as e:
            return f"Error generating paper: {str(e)}"

    def on_valves_updated(self):
        """Called when valve settings are updated."""
        pass
